import 'package:flutter/material.dart';

import 'bahag_icons.dart';

extension BahagIconsAll on BahagIcons {
  static List<IconDisplayInfo> get allIcons => [
        IconDisplayInfo('check', BahagIcons.minusProductDetail),
        IconDisplayInfo('checkMark', BahagIcons.checkMark),
        IconDisplayInfo('filterDiy', BahagIcons.filterDiy),
        IconDisplayInfo('plusProductDetail', BahagIcons.plusProductDetail),
        IconDisplayInfo('downward', BahagIcons.downward),
        IconDisplayInfo('qrCode', BahagIcons.qrCode),
        IconDisplayInfo('cart', BahagIcons.cart),
        IconDisplayInfo('heart', BahagIcons.heart),
        IconDisplayInfo('bookmarkFilledDiy', BahagIcons.bookmarkFilledDiy),
        IconDisplayInfo('clockDiy', BahagIcons.clockDiy),
        IconDisplayInfo('skillsThreeDiy', BahagIcons.skillsThreeDiy),
        IconDisplayInfo('skillsTwoDiy', BahagIcons.skillsTwoDiy),
        IconDisplayInfo('skillsOneDiy', BahagIcons.skillsOneDiy),
        IconDisplayInfo('commentsDiy', BahagIcons.commentsDiy),
        IconDisplayInfo('technicsDiy', BahagIcons.technicsDiy),
        IconDisplayInfo('backward', BahagIcons.backward),
        IconDisplayInfo('bookmarkDiy', BahagIcons.bookmarkDiy),
        IconDisplayInfo('tutorialDiy', BahagIcons.tutorialDiy),
        IconDisplayInfo(
            'inspirationLightBulbDiy', BahagIcons.inspirationLightBulbDiy),
        IconDisplayInfo('forward', BahagIcons.forward),
        IconDisplayInfo('info', BahagIcons.info),
        IconDisplayInfo('plus', BahagIcons.plus),
        IconDisplayInfo('closeSmall', BahagIcons.closeSmall),
        IconDisplayInfo('share', BahagIcons.share),
        IconDisplayInfo('trash', BahagIcons.trash),
        IconDisplayInfo('edit', BahagIcons.edit),
        IconDisplayInfo('privacyPolicy', BahagIcons.privacyPolicy),
        IconDisplayInfo('feedback', BahagIcons.feedback),
        IconDisplayInfo('paymentMethods', BahagIcons.paymentMethods),
        IconDisplayInfo('userProfile', BahagIcons.userProfile),
        IconDisplayInfo('coins', BahagIcons.coins),
        IconDisplayInfo('receipts', BahagIcons.receipts),
        IconDisplayInfo('purchases', BahagIcons.purchases),
        IconDisplayInfo('phone', BahagIcons.phone),
        IconDisplayInfo('qA', BahagIcons.qA),
        IconDisplayInfo('location', BahagIcons.location),
        IconDisplayInfo('barcode', BahagIcons.barcode),
        IconDisplayInfo('filter', BahagIcons.filter),
        IconDisplayInfo('favorite', BahagIcons.favorite),
        IconDisplayInfo('favoriteFilled', BahagIcons.favoriteFilled),
        IconDisplayInfo('upward', BahagIcons.upward),
        IconDisplayInfo('bottomNavbarCart', BahagIcons.bottomNavbarCart),
        IconDisplayInfo('bottomNavbarDiy', BahagIcons.bottomNavbarDiy),
        IconDisplayInfo(
            'bottomNavbarProducts', BahagIcons.bottomNavbarProducts),
        IconDisplayInfo('bottomNavbarHome', BahagIcons.bottomNavbarHome),
        IconDisplayInfo('search', BahagIcons.search),
        IconDisplayInfo('closeBig', BahagIcons.closeBig),
        IconDisplayInfo('correct', BahagIcons.correct),
        IconDisplayInfo('chainsaw', BahagIcons.chainsaw),
        IconDisplayInfo('lego', BahagIcons.lego),
        IconDisplayInfo('warranty', BahagIcons.warranty),
        IconDisplayInfo('opensource', BahagIcons.opensource),
        IconDisplayInfo('cookie', BahagIcons.cookie),
        IconDisplayInfo('agb', BahagIcons.agb),
        IconDisplayInfo('versions', BahagIcons.versions),
        IconDisplayInfo('imprint', BahagIcons.imprint),
        IconDisplayInfo('acceptanceCriteria', BahagIcons.acceptanceCriteria),
        IconDisplayInfo('rightsOfWithdrawal', BahagIcons.rightsOfWithdrawal),
        IconDisplayInfo('imageNotLoaded', BahagIcons.imageNotLoaded),
        IconDisplayInfo('minusCircleFill', BahagIcons.minusCircleFill),
        IconDisplayInfo('checkmarkCircleFill', BahagIcons.checkmarkCircleFill),
        IconDisplayInfo('circle', BahagIcons.circle),
        IconDisplayInfo('checkmarkRounded', BahagIcons.checkmarkRounded),
        IconDisplayInfo('flash', BahagIcons.flash),
        IconDisplayInfo('emptyOrder', BahagIcons.emptyOrder),
        IconDisplayInfo('emptyBox', BahagIcons.emptyBox),
        IconDisplayInfo('zoomPlus', BahagIcons.zoomplus),
        IconDisplayInfo('zoomMinus', BahagIcons.zoomminus),
        IconDisplayInfo('events', BahagIcons.events),
        IconDisplayInfo('shoppingList', BahagIcons.shoppinglist),
        IconDisplayInfo('route', BahagIcons.route),
        IconDisplayInfo('call', BahagIcons.call),
        IconDisplayInfo('onSite', BahagIcons.onSite),
        IconDisplayInfo('onSiteBarcode', BahagIcons.onSiteBarcode),
        IconDisplayInfo('legalInfo', BahagIcons.legalInfo),
        IconDisplayInfo('storeSearchEmpty', BahagIcons.storesearchempty),
      ];
}

class IconDisplayInfo {
  final String name;
  final IconData iconData;
  IconDisplayInfo(this.name, this.iconData);
}
